apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: runtime-plane-hpa
  namespace: aegisworld
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: runtime-plane
  minReplicas: 10
  maxReplicas: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

